# pyproject.toml

[tool.ruff]
line-length = 120
exclude = ["nifi/user-scripts/legacy_scripts", "tests/resources"]
target-version = "py38"

[tool.ruff.lint]
# E=pycodestyle, F=pyflakes, B=bugbear, I=isort
select = ["E", "F", "B", "I"]
fixable = ["ALL"]
