name: docker-jupyter-hub-hybrid-architecture

on:
  push:
    branches: ['**']
    tags: ['v*.*.*']
  pull_request:
    branches: ['**']
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: ubuntu-22.04
          - platform: arm64
            runner: ubuntu-22.04-arm

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Compute release tag
        id: release_version
        run: |
          if [[ "${GITHUB_REF#refs/heads/}" == "${GITHUB_REF}" ]]; then
            VERSION="${GITHUB_REF#refs/*/}"
          else
            VERSION="latest"
          fi
          echo "RELEASE_VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "release_version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build and push Jupyter Hub image
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: linux/${{ matrix.platform }}
          file: Dockerfile_hub
          build-args: |
            CPU_ARCHITECTURE=${{ matrix.platform }}
          tags: |
            cogstacksystems/jupyter-hub:${{ steps.release_version.outputs.release_version }}-${{ matrix.platform }}
          push: ${{ github.actor != 'dependabot[bot]' }}