name: docker-jupyter-singleuser-cpu-gpu-hybrid-architecture

on:

  push:
    branches: ['**']
    tags: ['v*.*.*']
  pull_request:
    branches: ['**']
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  CONTEXT: ./

jobs:
  setup:
    runs-on: ubuntu-22.04
    outputs:
      release_version: ${{ steps.release_version.outputs.release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Git Submodule Update
        run: |
          git submodule update --init --recursive
          git pull --recurse-submodules origin main
          git submodule update --remote --recursive

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            cogstacksystems/jupyter-singleuser:latest
      - name: Get and Set Release Version
        id: release_version
        run: |
          if [[ "${GITHUB_REF#refs/heads/}" == "${GITHUB_REF}" ]]; then
            # it's a tag or something else
            VERSION="${GITHUB_REF#refs/*/}"
          else
            VERSION="latest"
          fi
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "release_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Tag Setup
        run: |
          if [[ "${RELEASE_VERSION}" == "main" ]]; then
            echo "RELEASE_VERSION=latest" >> $GITHUB_ENV
          else
            echo "RELEASE_VERSION=${RELEASE_VERSION#?}" >> $GITHUB_ENV
          fi
  build-cpu:
    needs: setup
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - name: Build and Push CPU Image
        run: |
          docker build --platform linux/${{ matrix.platform }} \
            -t cogstacksystems/jupyter-singleuser:${{ needs.setup.outputs.release_version }}-${{ matrix.platform }} \
            -f Dockerfile_singleuser --build-arg CPU_ARCHITECTURE=${{ matrix.platform }} .
          docker push cogstacksystems/jupyter-singleuser:${{ needs.setup.outputs.release_version }}-${{ matrix.platform }}

  build-gpu:
    needs: setup
    runs-on: ubuntu-22.04
    steps:
      - name: Build and Push GPU Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT }}
          platforms: linux/amd64
          file: Dockerfile_singleuser_gpu
          build-args: |
            CPU_ARCHITECTURE=amd64
          tags: |
            cogstacksystems/jupyter-singleuser-gpu:${{ needs.setup.outputs.release_version }}-amd64
          push: true