name: docker-jupyter-singleuser-cpu-gpu-hybrid-architecture

on:
  push:
    branches: ['**']
    tags: ['v*.*.*']
  pull_request:
    branches: ['**']
  release:
    types: [published]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-22.04
    outputs:
      release_version: ${{ steps.release_version.outputs.release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Git Submodule Update
        run: |
          git submodule update --init --remote --recursive

      - name: Metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: cogstacksystems/jupyter-singleuser:latest

      - name: Get and Set Release Version
        id: release_version
        run: |
          if [[ "${GITHUB_REF#refs/heads/}" == "${GITHUB_REF}" ]]; then
            VERSION="${GITHUB_REF#refs/*/}"
          else
            VERSION="latest"
          fi
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "release_version=$VERSION" >> $GITHUB_OUTPUT

  build-cpu:
    needs: setup
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push CPU Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/${{ matrix.platform }}
          file: Dockerfile_singleuser
          build-args: |
            CPU_ARCHITECTURE=${{ matrix.platform }}
          tags: cogstacksystems/jupyter-singleuser:${{ needs.setup.outputs.release_version }}-${{ matrix.platform }}
          push: ${{ github.actor != 'dependabot[bot]' }}

  build-gpu:
    needs: setup
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push GPU Image
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: linux/amd64
          file: Dockerfile_singleuser_gpu
          build-args: |
            CPU_ARCHITECTURE=amd64
          tags: cogstacksystems/jupyter-singleuser-gpu:${{ needs.setup.outputs.release_version }}-amd64
          push: ${{ github.actor != 'dependabot[bot]' }}